---
- name: build a ospf network
  hosts: huawei
  gather_facts: no 
  connection: local
  vars:
    cli:
      host: "{{ ansible_host }}"
      port: 22
      username: huawei
      password: Tt123!123
      transport: cli

  tasks:
    - name: configure physical interface
      ce_config:
        lines:
          - undo portswitch
          - description OSPF Area 0 to {{ item.neighbor_name }}
          - ip address {{ item.int_ip | ipaddr('address') }} {{ item.int_ip | ipaddr('netmask') }}
          - undo shutdown
        parents: interface {{ item.int_name }}
        provider: "{{ cli }}"
      loop: "{{ physical_port }}"

    - name: configure ospf interface
      ce_config:
        lines:
          - area 0
          - network {{item.int_ip | ipaddr('network') }} {{ item.int_ip | ipaddr('hostmask') }}
        parents: ospf 1
        provider: "{{ cli }}"
      loop: "{{ physical_port }}"

    - name: pause to wailt the OSPF peer up
      pause:
        seconds: 60

    - name: verify the neighbor status
      ce_command:
        commands:
          - displau ospf peer brief | include {{ item_int_name }}
        provider: "{{ cli }}"
      register: ospf_peer_output 
      loop: "{{ physical_port }}"

    - name: output the neighbor status
      debug:
        msg: "The OSPF neighbor is up and the detail is Area {{ item.stdout[0] | regex_search('(0.0.0.0.*full)') }}"
      when: "full in item.stdout[0]"
      loop: "{{ ospf_peer_output.results }}" 
